#!/bin/env bash

# Used to backup the system root to a specified destination.

# TODO: Add restore option
# TODO: Try and handle files being changed during the copy

SRC='\'

script_name="$(basename $0)"
dest="$1"

usage() {
	printf "%s [destination]\n" "${script_name}"
}

if [[ $# -ne 1 ]]; then
	usage

	exit 1
fi

rsync \
	--archive \
	--acls \
	--xattrs \
	--exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} \
	"${SRC}" \
	"${dest}"

exit 0
